name: Build Flutter (Android APK)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-android-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get project version from pubspec.yaml
        id: get_version
        run: echo "version_name=$(grep 'version:' pubspec.yaml | cut -d ' ' -f 2 | cut -d '+' -f 1)" >> $GITHUB_OUTPUT
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'
          channel: 'stable'
          cache: true
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze project
        run: flutter analyze
      - name: Run tests
        run: flutter test
      - name: Build Android APK
        run: flutter build apk --release --build-name=${{ steps.get_version.outputs.version_name }} --build-number=${{ github.run_number }}
      - name: Rename APK file
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/app-v${{ steps.get_version.outputs.version_name }}-${{ github.run_number }}.apk

      - name: Create GitHub Release
        if: github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version_name }}-${{ github.run_number }}
          name: Release v${{ steps.get_version.outputs.version_name }} (Build ${{ github.run_number }})
          generate_release_notes: true
          prerelease: true
          files: |
            build/app/outputs/flutter-apk/app-v${{ steps.get_version.outputs.version_name }}-${{ github.run_number }}.apk